server:
  port: 8888
  tomcat:
    max-threads: 10
    uri-encoding: UTF-8
    max-connections: 50
    accept-count: 20

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/